"""Darwin v50 evidence-first causal kernel.

This package deliberately makes no claims about consciousness, general
intelligence, language understanding, or autonomous learning.  Its first job is
to make causal claims inspectable and false successes difficult to represent.
"""

from .kernel import DarwinKernelV50
from .capabilities import (
    CapabilityApprovalSigner,
    CapabilityApprovalVerifier,
    CapabilityGrant,
    workspace_scope,
)
from .evidence import (
    ActionRequest,
    HMACObservationSigner,
    HMACObservationVerifier,
    ObservationEnvelope,
)
from .consent import (
    ED25519_CONSENT_SCHEME,
    HMAC_CONSENT_SCHEME,
    INTERACTIVE_TTY_CHANNEL,
    TEST_HARNESS_CHANNEL,
    ConsentError,
    ConsentReceipt,
    ConsentReceiptSigner,
    ConsentReceiptVerifier,
    ConsentRequest,
    ConsentRisk,
    InteractiveConsentGate,
)
from .asymmetric_consent import (
    Ed25519ConsentReceiptSigner,
    Ed25519ConsentReceiptVerifier,
    public_key_fingerprint,
)
from .executor import CapabilityWorkspaceExecutor
from .subprocess_executor import SubprocessWorkspaceExecutor
from .isolation import (
    IsolationAssessment,
    IsolationMechanism,
    IsolationPolicyError,
    require_os_security_boundary,
    same_user_subprocess_assessment,
)
from .windows_isolation import (
    AppContainerTokenEvidence,
    WindowsIsolationAvailability,
    current_process_appcontainer_evidence,
    probe_windows_isolation_availability,
)
from .cognitive_lab import (
    ActiveTransitionExplorer,
    CausalEnvironment,
    ExplorationTrace,
    LabObservation,
    LabStep,
    ModelBasedPlanner,
    ModelPlan,
    OpaqueGraphWorld,
    TabularTransitionModel,
    TransitionExperience,
    TransitionPrediction,
    collect_controlled_transition_census,
    make_benchmark_world,
)
from .uncertainty_lab import (
    BetaBernoulliOutcomeModel,
    HiddenSignalObservation,
    HiddenSignalWorld,
    InformationDecision,
    OutcomeExperience,
    OutcomeForecast,
    SelectiveInformationPolicy,
)
from .temporal_lab import (
    AdaptiveBernoulliForecaster,
    BinaryForecast,
    BinaryStreamObservation,
    ChangeDetection,
    FixedWindowBernoulliForecaster,
    RegimeShiftBernoulliStream,
    StationaryBernoulliForecaster,
    TwoWindowMeanShiftDetector,
)
from .drift_lab import (
    FixedShareMemoryForecaster,
    MultiphaseBernoulliStream,
    MultiscaleForecast,
)
from .run_length_lab import (
    PrunedBayesianRunLengthForecaster,
    RunLengthForecast,
    RunLengthHypothesis,
    VariableRegimeBernoulliStream,
    VariableRegimeSchedule,
)
from .regime_memory_lab import (
    RegimeMemoryBernoulliStream,
    RegimeMemoryForecast,
    RegimeMemorySchedule,
    RegimeMemoryTransition,
    RegimePrototype,
    RegimeRepositoryForecaster,
)
from .adaptive_arbitration_lab import (
    AdaptiveArbitrationForecast,
    AdaptiveMemoryArbitrator,
    AgeBinnedExpertWeights,
    ArbitrationBernoulliStream,
    ArbitrationSchedule,
    ExpertWeightDecision,
)
from .episodic_context_lab import (
    ContextDefinition,
    EpisodeRetrievalDecision,
    EpisodicActionMemory,
    EpisodicContextWorld,
    EpisodicInteraction,
    EpisodicPrototype,
    EpisodicStep,
    EpisodicWorldSpecification,
)
from .predictive_planning_lab import (
    HistoryFrontierExplorer,
    HistoryTransitionRule,
    PredictiveHistoryModel,
    PredictiveHistoryPlan,
    PredictiveHistoryPlanner,
    PredictivePlanningObservation,
    PredictivePlanningStep,
    PredictivePlanningWorld,
    PredictiveTransitionExperience,
    PredictiveTransitionPrediction,
    PredictiveWorldSpecification,
)
from .learned_context_lab import (
    CausalContextArchive,
    ContextDynamicsRule,
    ContextOrderScore,
    ContextOutcomeCounts,
    ContextValuePlanner,
    LearnedContextExperience,
    LearnedContextModel,
    LearnedContextObservation,
    LearnedContextStep,
    LearnedContextWorld,
    LearnedContextWorldSpecification,
    RewardContext,
)
from .online_posterior_lab import (
    BetaCounts,
    FiniteHorizonContextPlanner,
    OnlineBayesianModel,
    OnlineCausalArchive,
    OnlineExperience,
    OnlinePosteriorAgent,
    OutcomeCounts,
    ProbabilityTableModel,
)
from .information_directed_lab import (
    InformationDirectedAgent,
    InformationDirectedDecision,
)
from .models import (
    ComparisonCondition,
    ComparisonOperator,
    Goal,
    GoalStateError,
    GoalStatus,
    ObservationResult,
)
from .store import SQLiteEventStore
from .language import (
    DarwinLanguageGateway,
    ExpressionPlan,
    GroundedFact,
    KnowledgeCandidate,
    KnowledgeQuery,
    KnowledgeStatus,
    LanguageAuthorityError,
    LanguageBackendError,
    LanguageBoundaryError,
    LanguageExpression,
    LanguageMode,
    LanguageModelBackend,
    LanguageModelRequest,
    LanguageObservation,
    LanguageOperation,
    ObservedEntity,
    ReportedSignal,
    UnderstandingRequest,
)

__all__ = [
    "ActiveTransitionExplorer",
    "AdaptiveArbitrationForecast",
    "AdaptiveBernoulliForecaster",
    "AdaptiveMemoryArbitrator",
    "AgeBinnedExpertWeights",
    "ArbitrationBernoulliStream",
    "ArbitrationSchedule",
    "BinaryForecast",
    "BinaryStreamObservation",
    "ChangeDetection",
    "ComparisonCondition",
    "ComparisonOperator",
    "ActionRequest",
    "AppContainerTokenEvidence",
    "BetaBernoulliOutcomeModel",
    "BetaCounts",
    "CapabilityApprovalSigner",
    "CapabilityApprovalVerifier",
    "CapabilityGrant",
    "CapabilityWorkspaceExecutor",
    "CausalEnvironment",
    "CausalContextArchive",
    "ConsentError",
    "ConsentReceipt",
    "ConsentReceiptSigner",
    "ConsentReceiptVerifier",
    "ConsentRequest",
    "ConsentRisk",
    "ContextDefinition",
    "ContextDynamicsRule",
    "ContextOrderScore",
    "ContextOutcomeCounts",
    "ContextValuePlanner",
    "DarwinKernelV50",
    "DarwinLanguageGateway",
    "ExpressionPlan",
    "GroundedFact",
    "KnowledgeCandidate",
    "KnowledgeQuery",
    "KnowledgeStatus",
    "LanguageAuthorityError",
    "LanguageBackendError",
    "LanguageBoundaryError",
    "LanguageExpression",
    "LanguageMode",
    "LanguageModelBackend",
    "LanguageModelRequest",
    "LanguageObservation",
    "LanguageOperation",
    "ObservedEntity",
    "ReportedSignal",
    "UnderstandingRequest",
    "EpisodeRetrievalDecision",
    "EpisodicActionMemory",
    "EpisodicContextWorld",
    "EpisodicInteraction",
    "EpisodicPrototype",
    "EpisodicStep",
    "EpisodicWorldSpecification",
    "Goal",
    "GoalStateError",
    "GoalStatus",
    "HMACObservationSigner",
    "HMACObservationVerifier",
    "HMAC_CONSENT_SCHEME",
    "HiddenSignalObservation",
    "HiddenSignalWorld",
    "HistoryFrontierExplorer",
    "HistoryTransitionRule",
    "ED25519_CONSENT_SCHEME",
    "Ed25519ConsentReceiptSigner",
    "Ed25519ConsentReceiptVerifier",
    "ExplorationTrace",
    "ExpertWeightDecision",
    "FixedWindowBernoulliForecaster",
    "FixedShareMemoryForecaster",
    "FiniteHorizonContextPlanner",
    "INTERACTIVE_TTY_CHANNEL",
    "InteractiveConsentGate",
    "InformationDecision",
    "InformationDirectedAgent",
    "InformationDirectedDecision",
    "IsolationAssessment",
    "IsolationMechanism",
    "IsolationPolicyError",
    "LabObservation",
    "LabStep",
    "LearnedContextExperience",
    "LearnedContextModel",
    "LearnedContextObservation",
    "LearnedContextStep",
    "LearnedContextWorld",
    "LearnedContextWorldSpecification",
    "ModelBasedPlanner",
    "ModelPlan",
    "MultiphaseBernoulliStream",
    "MultiscaleForecast",
    "ObservationResult",
    "ObservationEnvelope",
    "OnlineBayesianModel",
    "OnlineCausalArchive",
    "OnlineExperience",
    "OnlinePosteriorAgent",
    "OutcomeExperience",
    "OutcomeCounts",
    "OutcomeForecast",
    "OpaqueGraphWorld",
    "PrunedBayesianRunLengthForecaster",
    "PredictiveHistoryModel",
    "PredictiveHistoryPlan",
    "PredictiveHistoryPlanner",
    "PredictivePlanningObservation",
    "PredictivePlanningStep",
    "PredictivePlanningWorld",
    "PredictiveTransitionExperience",
    "PredictiveTransitionPrediction",
    "PredictiveWorldSpecification",
    "ProbabilityTableModel",
    "RegimeShiftBernoulliStream",
    "RegimeMemoryBernoulliStream",
    "RegimeMemoryForecast",
    "RegimeMemorySchedule",
    "RegimeMemoryTransition",
    "RegimePrototype",
    "RegimeRepositoryForecaster",
    "RewardContext",
    "RunLengthForecast",
    "RunLengthHypothesis",
    "SQLiteEventStore",
    "SubprocessWorkspaceExecutor",
    "SelectiveInformationPolicy",
    "StationaryBernoulliForecaster",
    "TabularTransitionModel",
    "TEST_HARNESS_CHANNEL",
    "WindowsIsolationAvailability",
    "TransitionExperience",
    "TransitionPrediction",
    "TwoWindowMeanShiftDetector",
    "VariableRegimeBernoulliStream",
    "VariableRegimeSchedule",
    "collect_controlled_transition_census",
    "current_process_appcontainer_evidence",
    "probe_windows_isolation_availability",
    "require_os_security_boundary",
    "public_key_fingerprint",
    "make_benchmark_world",
    "same_user_subprocess_assessment",
    "workspace_scope",
]

__version__ = "0.1.0"
